### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by fconstance** [kondratevakate/3DDeformableConvolutions#2]
Hello !
Thank you very much for you code, it's very nice.
I've taken your 3D deformable convolution to replace the last 3D "classical" convolutions in my own network. 
However, I'm facing a huge increase in memory usage. Do you face a similar issue?
Thanks !
Constance

**Comment by kondratevakate** [comment]
It is normal since deformable convoltuon contains an addtiional convolutional layer that predicts sampling locations for the main convolutional kernel at each image point. For a 3D image and 3x3x3 kernel, we have to predict three-dimenstional offset vector for each of 27 sampling locations at each image point. So, basically, each 3x3x3 deformable convolution explicitly produces 81 feature maps (in addition to the main output). 
To reduce the memory, one can place deformable convolutions in the deeper convolutional layers, where spatial size of the feature maps is lower.

**Comment by fconstance** [comment]
Thank you very much for your answer, it's very clear :)

**Comment by stanny880913** [comment]
> Hello ! Thank you very much for you code, it's very nice. I've taken your 3D deformable convolution to replace the last 3D "classical" convolutions in my own network. However, I'm facing a huge increase in memory usage. Do you face a similar issue? Thanks ! Constance

Hello，may I ask you how to use 3D deformable convolution to replace the last 3D "classical" convolutions!
thank  you
